require("generator/service-authority.scala")
require("generator/service-cpv.scala")
require("generator/service-form.scala")
require("generator/service-measurement_unit.scala")
require("generator/service-supplier.scala")
